server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/my_blog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: blog_user
    password: 123456

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunshinerao.myblog.entity
  #驼峰映射
  configuration:
    map-underscore-to-camel-case: true